### ISSUE TITLE
Klyte.ServiceVehiclesManager.Overrides.OutsideConnectionAIOverrides.StartTransferOverride 

### ISSUE THREAD

**Issue by originalfoo** [klyte45/ServiceVehiclesManager#3]
User reported error on the TM:PE issue tracker: https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/121

Looks like it's something to do with your mod? Might have been fixed recently -- if so, could you make a note on the linked issue?

**Comment by klyte45** [comment]
I checked this log and the code, then I think this is not related to SVM. The null checking in the info is being done before sending it to create the vehicle. So, it must be a corrupt asset problem.

**Comment by Machine-Maker** [comment]
Ok, thanks for letting me know.
