### ISSUE TITLE
Latest Patch Prevents Service Vehicle Manager From Working

### ISSUE THREAD

**Issue by JukEboXAuDiO** [klyte45/ServiceVehiclesManager#7]
Hi Klyte. First off I am a HUGE fan of your MODS! Thank you for all your work. Best of all is the Service Vehicle Manager. Its my favorite MOD. Specifically because it has the window to view what vehicle your selecting. INVALUABLE.

Anyway the game updated to day and now SVM will not work. That stupid button on the bottom of service building where they added a button to select the vehicle from the building is causing a conflict. See the screenshots. 

Example is this police station. Normally that button is set to random which is how SVM normally works. Now they are default set to the default vehicle (i.e. police car in this case). In SVM I have this building set to have the Arizona DPS Tahoe & Explorer. But all it does is spawn Police Cars (default one). It only spawns something else if I select it. But if I select random I get an error.

This has now taken precedence over SVM and now SVM will do nothing to services with this button. Anything you can do?

![20220210221452_1](https://user-images.githubusercontent.com/23240585/153534506-b6561507-8569-4bb4-a40e-5bf80e9e5d94.jpg)
![Inked20220210221502_1_LI](https://user-images.githubusercontent.com/23240585/153534498-56548da6-6537-4d97-b418-7e4391b60a73.jpg)

**Comment by klyte45** [comment]
Wait: It's about old Service Vehicle Manager or about Vehicle Master Control? I got confused 🙃

**Comment by JukEboXAuDiO** [comment]
Sorry for late reply. This was actually a problem with the official. Fixed by patch after Airports.
